<!--NAVIGATION-->


<a href="https://colab.research.google.com/github/jttoivon/x/blob/master/pandas.ipynb"><img align="left" src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab" title="Open and Execute in Google Colaboratory"></a>


# Pandas

In the NumPy section we dealt with some arrays, whose columns had each a special meaning. For example, the column number 0 could contains values interpreted as years, and column 1 could contain a month, and so on. It is possible to handle the data this way, but in can be hard to remember, which column number corresponds to which variable. Especially, if you later remove some column from the array, then the numbering of the remaining columns changes. One solution to this is to give a descriptive name to each column. These column names stay fixed and attached to their corresponding columns, even if we remove some of the columns. In addition, the rows can be given names as well, these are called *indices* in Pandas.

The *Pandas* library is build on top of the NumPy library, and it provides a special kind of two dimensional data structure called `DataFrame`. The `DataFrame` allows to give names to the columns, so that one can access a column using its name inplace of the index of the column.

The quickly go through few examples to see what is possible with Pandas. It is typical to import the Pandas library as the shorthand `pd`.

In [17]:
import pandas as pd    # This is the standard way of importing the Pandas library
import numpy as np

In [3]:
wh = pd.read_csv("https://www.cs.helsinki.fi/u/jttoivon/dap/data/fmi/kumpula-weather-2017.csv")
wh.head()   # The head method prints the first 5 rows

Year  m  d   Time Time zone  Precipitation amount (mm)  Snow depth (cm)  \
0  2017  1  1  00:00       UTC                       -1.0             -1.0   
1  2017  1  2  00:00       UTC                        4.4             -1.0   
2  2017  1  3  00:00       UTC                        6.6              7.0   
3  2017  1  4  00:00       UTC                       -1.0             13.0   
4  2017  1  5  00:00       UTC                       -1.0             10.0   

   Air temperature (degC)  
0                     0.6  
1                    -3.9  
2                    -6.5  
3                   -12.8  
4                   -17.8

Now we can refer to a column by its name:

In [4]:
wh["Snow depth (cm)"].head()     # Using the tab key can help enter long column names

0    -1.0
1    -1.0
2     7.0
3    13.0
4    10.0
Name: Snow depth (cm), dtype: float64

In [5]:
wh["Air temperature (degC)"].mean()    # Mean temperature

6.527123287671233

In [6]:
wh.drop("Time zone", axis=1).head()    # Return a copy with one column removed, the original DataFrame stays intact

Year  m  d   Time  Precipitation amount (mm)  Snow depth (cm)  \
0  2017  1  1  00:00                       -1.0             -1.0   
1  2017  1  2  00:00                        4.4             -1.0   
2  2017  1  3  00:00                        6.6              7.0   
3  2017  1  4  00:00                       -1.0             13.0   
4  2017  1  5  00:00                       -1.0             10.0   

   Air temperature (degC)  
0                     0.6  
1                    -3.9  
2                    -6.5  
3                   -12.8  
4                   -17.8

In [7]:
wh.head()

Year  m  d   Time Time zone  Precipitation amount (mm)  Snow depth (cm)  \
0  2017  1  1  00:00       UTC                       -1.0             -1.0   
1  2017  1  2  00:00       UTC                        4.4             -1.0   
2  2017  1  3  00:00       UTC                        6.6              7.0   
3  2017  1  4  00:00       UTC                       -1.0             13.0   
4  2017  1  5  00:00       UTC                       -1.0             10.0   

   Air temperature (degC)  
0                     0.6  
1                    -3.9  
2                    -6.5  
3                   -12.8  
4                   -17.8

We will now go through systematically through the DataFrame and its one-dimensional version: *Series*.

## Creation and indexing of series

One can turn any one-dimensional iterable into a Series:

In [99]:
s=pd.Series([1, 4, 5, 2, 5, 2])
s

0    1
1    4
2    5
3    2
4    5
5    2
dtype: int64

The data type of the elements in the Series is `int64`, integers representable in 64 bits. 

We can also attach a name to this series:

In [82]:
s.name = "Grades"
s

0    1
1    4
2    2
3    2
4    5
Name: Grades, dtype: int64

The common attributes of the series are the `name`, `dtype`, and `size`:

In [88]:
print("Name: %s, dtype: %s, size: %s" % (s.name, s.dtype, s.size))

Name: Grades, dtype: int64, size: 5


In addition to the values of the series, also the row indices were printed. All the accessing methods from NumPy arrays also work for the Series: indexing, slicing, and fancy indexing. 

In [100]:
s[1]

4

In [110]:
s2=s[[0,5]]                    # Fancy indexing

In [111]:
t=s[-2:]                    # Slicing
t

4    5
5    2
dtype: int64

Note that the indices stick to the corresponding values, they are not renumbered!

In [112]:
t[4]                        # t[0] would give an error

5

The values as a NumPy array are accessible with the `values` attribute:

In [113]:
s2.values

array([1, 2])

And the indices are available through the `index` attribute:

In [114]:
s2.index

Int64Index([0, 5], dtype='int64')

The index is not simply a NumPy array, but a data structure that allows fast access to the elements. The indices need not be integers, as the next example shows:

In [116]:
s3=pd.Series([1, 4, 5, 2, 5, 2], index=list("abcdef"))
s3

a    1
b    4
c    5
d    2
e    5
f    2
dtype: int64

In [117]:
s3.index

Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='object')

In [119]:
s3["b"]

4

<div class="alert alert-warning">
Note a special case here: if the indices are not integers, then the last index of the slice is included in the result. This is contrary to slicing with integers!
</div>

In [127]:
s3["b":"e"]

b    4
c    5
d    2
e    5
dtype: int64

If one really must, then one can also access the Series through the *implicit integers index*. This indexing works exactly like in NumPy. The `iloc` attribute allows accessing using integers:

In [125]:
for i in range(s3.size):
    print(i, s3.iloc[i])

0 1
1 4
2 5
3 2
4 5
5 2


One may notice that there are similarities between Python's dictionaries and Pandas' Series, both can be thought to access values using keys. The difference is that Series requires that the indices have all the same type, and similarly, all the values have the same type. This restriction allows creation of fast data structures.

As a mark of the similaries between these two data structures, Pandas allows creation of a `Series` object from a dictionary:

In [131]:
d = { 2001 : "Bush", 2005: "Bush", 2009: "Obama", 2013: "Obama", 2017 : "Trump"}
s4 = pd.Series(d, name="Presidents")
s4

2001     Bush
2005     Bush
2009    Obama
2013    Obama
2017    Trump
Name: Presidents, dtype: object

## Creation of dataframes

## Accessing columns of a dataframe. Results in
* a series
* a dataframe with n columns (n=0,1,2,...)

## Other indexing and data selection

## Summary statistics

The summary statistic methods work in a similar way as their counter parts in NumPy. By default, the aggregation is done over columns.

In [19]:
wh2 = wh.drop(["Year", "m", "d"], axis=1)  # taking averages over these is not very interesting
wh2.mean()

Precipitation amount (mm)    1.966301
Snow depth (cm)              0.966480
Air temperature (degC)       6.527123
dtype: float64

The `describe` method of the `DataFrame` object gives different summary statistics for each (numeric) column. The result is a DataFrame. This method gives a good overview of the data.

In [16]:
wh.describe()

Year           m           d  Precipitation amount (mm)  \
count   365.0  365.000000  365.000000                 365.000000   
mean   2017.0    6.526027   15.720548                   1.966301   
std       0.0    3.452584    8.808321                   4.858423   
min    2017.0    1.000000    1.000000                  -1.000000   
25%    2017.0    4.000000    8.000000                  -1.000000   
50%    2017.0    7.000000   16.000000                   0.200000   
75%    2017.0   10.000000   23.000000                   2.700000   
max    2017.0   12.000000   31.000000                  35.000000   

       Snow depth (cm)  Air temperature (degC)  
count       358.000000              365.000000  
mean          0.966480                6.527123  
std           3.717472                7.183934  
min          -1.000000              -17.800000  
25%          -1.000000                1.200000  
50%          -1.000000                4.800000  
75%           0.000000               12.900000  
max          15.000000               19.600000

WHY IS COUNT OF SNOW ONLY 358?

In [28]:
wh[wh.isnull().any(axis=1)]

Year   m   d   Time Time zone  Precipitation amount (mm)  \
74   2017   3  16  00:00       UTC                        1.8   
163  2017   6  13  00:00       UTC                        0.6   
308  2017  11   5  00:00       UTC                        0.2   
309  2017  11   6  00:00       UTC                        2.0   
313  2017  11  10  00:00       UTC                        3.6   
321  2017  11  18  00:00       UTC                       11.3   
328  2017  11  25  00:00       UTC                        8.5   

     Snow depth (cm)  Air temperature (degC)  
74               NaN                     3.4  
163              NaN                    12.6  
308              NaN                     8.4  
309              NaN                     7.5  
313              NaN                     7.2  
321              NaN                     5.9  
328              NaN                     4.2

## Missing data

You may have noticed something strange in the output of the describe method: the snow depth column has count 358, whereas the other columns have count 365, one measurement/value for each day of the year. How is this possible? Let's use the `unique` method of the Series object to find out, which different values are used in this column:

In [6]:
wh["Snow depth (cm)"].unique()

array([-1.,  7., 13., 10., 12.,  9.,  8.,  5.,  6.,  4.,  3., 15., 14.,
        2., nan,  0.])

The `float` type allows a special value `nan` (Not A Number), in addition to normal floating point numbers. This value can represent the result from an illegal operation. For example, the operation 0/0 can either cause an exception to occur or just silently produce a `nan`. In Pandas `nan` can be used to represent a missing value. In the weather DataFrame the `nan` value tells us that the measurement from that day is not available, possibly due to a broken measuring instrument or some other problem.

Note that only float types allow the `nan` value. So, if we try to create an integer series with missing values, its dtype gets promoted to `float`:

In [23]:
pd.Series([1,3,2])

0    1
1    3
2    2
dtype: int64

In [26]:
pd.Series([1,3,2, np.nan])

0    1.0
1    3.0
2    2.0
3    NaN
dtype: float64

For non-numeric types the special value `None` is used to denote the missing value, and the dtype is promoted to `object`.

In [27]:
pd.Series(["jack", "joe", None])

0    jack
1     joe
2    None
dtype: object

Pandas excludes the missing values from the summary statistics, like we saw in the previous section. Pandas also provides some functions to handle missing values.

The `dropna` method of a DataFrame drops columns or rows that contain missing values from the DataFrame, depending on the `axis` parameter.

In [29]:
wh.dropna().shape   # Default axis is 0

(358, 8)

In [31]:
wh.dropna(axis=1).shape # Drops the columns containing missing values

(365, 7)

The `how` and `thresh` parameters of the `dropna` method allow one to specify how many values need to be missing in order the row/column to be dropped.

In [22]:
wh[wh["m"]==11]

Year   m   d   Time Time zone  Precipitation amount (mm)  \
304  2017  11   1  00:00       UTC                       -1.0   
305  2017  11   2  00:00       UTC                        0.1   
306  2017  11   3  00:00       UTC                        0.3   
307  2017  11   4  00:00       UTC                        1.0   
308  2017  11   5  00:00       UTC                        0.2   
309  2017  11   6  00:00       UTC                        2.0   
310  2017  11   7  00:00       UTC                       -1.0   
311  2017  11   8  00:00       UTC                        0.2   
312  2017  11   9  00:00       UTC                        9.3   
313  2017  11  10  00:00       UTC                        3.6   
314  2017  11  11  00:00       UTC                       16.7   
315  2017  11  12  00:00       UTC                        2.2   
316  2017  11  13  00:00       UTC                       -1.0   
317  2017  11  14  00:00       UTC                        2.1   
318  2017  11  15  00:00       UTC                        1.1   
319  2017  11  16  00:00       UTC                        1.8   
320  2017  11  17  00:00       UTC                        2.0   
321  2017  11  18  00:00       UTC                       11.3   
322  2017  11  19  00:00       UTC                       10.4   
323  2017  11  20  00:00       UTC                        4.5   
324  2017  11  21  00:00       UTC                        2.5   
325  2017  11  22  00:00       UTC                        1.5   
326  2017  11  23  00:00       UTC                        6.2   
327  2017  11  24  00:00       UTC                        9.0   
328  2017  11  25  00:00       UTC                        8.5   
329  2017  11  26  00:00       UTC                        5.5   
330  2017  11  27  00:00       UTC                        4.7   
331  2017  11  28  00:00       UTC                        8.3   
332  2017  11  29  00:00       UTC                        2.1   
333  2017  11  30  00:00       UTC                        3.1   

     Snow depth (cm)  Air temperature (degC)  
304              0.0                     0.1  
305              0.0                     0.5  
306             -1.0                     3.2  
307             -1.0                     8.0  
308              NaN                     8.4  
309              NaN                     7.5  
310             -1.0                     3.9  
311             -1.0                     5.9  
312             -1.0                     6.7  
313              NaN                     7.2  
314             -1.0                     5.9  
315             -1.0                     3.1  
316             -1.0                     2.4  
317             -1.0                     1.8  
318             -1.0                     3.1  
319             -1.0                     3.5  
320             -1.0                     5.8  
321              NaN                     5.9  
322             -1.0                     4.0  
323             -1.0                     1.2  
324              3.0                     0.9  
325             -1.0                     1.0  
326             -1.0                     1.5  
327             -1.0                     6.1  
328              NaN                     4.2  
329             -1.0                     2.3  
330             -1.0                     4.6  
331             -1.0                     3.9  
332             -1.0                     2.8  
333             -1.0                     3.1

In [18]:
np.sort(wh["Precipitation amount (mm)"].unique())

array([-1. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3.1,  3.2,  3.3,  3.4,
        3.5,  3.6,  3.7,  3.9,  4.1,  4.2,  4.3,  4.4,  4.5,  4.6,  4.7,
        4.9,  5. ,  5.1,  5.2,  5.3,  5.4,  5.5,  5.6,  5.7,  5.9,  6. ,
        6.1,  6.2,  6.4,  6.6,  6.9,  7.2,  7.6,  7.7,  7.8,  8. ,  8.3,
        8.5,  9. ,  9.3,  9.4,  9.9, 10. , 10.3, 10.4, 11. , 11.3, 11.7,
       12.2, 12.3, 12.7, 14.1, 15.4, 15.9, 16.3, 16.4, 16.7, 17.1, 18.1,
       18.3, 18.6, 19.6, 21.5, 24.2, 26.5, 35. ])

In [ ]:
wh["Precipitation amount (mm)"].unique().sort

In [19]:
wh[wh["Snow depth (cm)"]!=-1]

Year   m   d   Time Time zone  Precipitation amount (mm)  \
2    2017   1   3  00:00       UTC                        6.6   
3    2017   1   4  00:00       UTC                       -1.0   
4    2017   1   5  00:00       UTC                       -1.0   
5    2017   1   6  00:00       UTC                        0.3   
6    2017   1   7  00:00       UTC                        5.3   
7    2017   1   8  00:00       UTC                       -1.0   
8    2017   1   9  00:00       UTC                        1.1   
9    2017   1  10  00:00       UTC                        0.3   
10   2017   1  11  00:00       UTC                       -1.0   
11   2017   1  12  00:00       UTC                        8.0   
12   2017   1  13  00:00       UTC                        0.1   
13   2017   1  14  00:00       UTC                        0.1   
14   2017   1  15  00:00       UTC                       -1.0   
15   2017   1  16  00:00       UTC                       -1.0   
16   2017   1  17  00:00       UTC                        0.2   
17   2017   1  18  00:00       UTC                        0.9   
18   2017   1  19  00:00       UTC                       -1.0   
19   2017   1  20  00:00       UTC                        0.3   
20   2017   1  21  00:00       UTC                        0.4   
21   2017   1  22  00:00       UTC                        0.2   
22   2017   1  23  00:00       UTC                        0.1   
23   2017   1  24  00:00       UTC                       -1.0   
24   2017   1  25  00:00       UTC                        0.6   
25   2017   1  26  00:00       UTC                       -1.0   
26   2017   1  27  00:00       UTC                       -1.0   
27   2017   1  28  00:00       UTC                        1.8   
28   2017   1  29  00:00       UTC                        2.6   
29   2017   1  30  00:00       UTC                        5.6   
30   2017   1  31  00:00       UTC                       -1.0   
31   2017   2   1  00:00       UTC                        1.5   
..    ...  ..  ..    ...       ...                        ...   
74   2017   3  16  00:00       UTC                        1.8   
79   2017   3  21  00:00       UTC                        6.0   
89   2017   3  31  00:00       UTC                        0.6   
102  2017   4  13  00:00       UTC                        0.3   
114  2017   4  25  00:00       UTC                        4.9   
119  2017   4  30  00:00       UTC                        0.4   
163  2017   6  13  00:00       UTC                        0.6   
293  2017  10  21  00:00       UTC                       -1.0   
296  2017  10  24  00:00       UTC                       -1.0   
298  2017  10  26  00:00       UTC                       12.3   
299  2017  10  27  00:00       UTC                        2.7   
300  2017  10  28  00:00       UTC                       17.1   
304  2017  11   1  00:00       UTC                       -1.0   
305  2017  11   2  00:00       UTC                        0.1   
308  2017  11   5  00:00       UTC                        0.2   
309  2017  11   6  00:00       UTC                        2.0   
313  2017  11  10  00:00       UTC                        3.6   
321  2017  11  18  00:00       UTC                       11.3   
324  2017  11  21  00:00       UTC                        2.5   
328  2017  11  25  00:00       UTC                        8.5   
335  2017  12   2  00:00       UTC                        5.3   
340  2017  12   7  00:00       UTC                       16.3   
346  2017  12  13  00:00       UTC                        4.2   
347  2017  12  14  00:00       UTC                        5.2   
348  2017  12  15  00:00       UTC                       10.0   
349  2017  12  16  00:00       UTC                        1.3   
350  2017  12  17  00:00       UTC                       -1.0   
351  2017  12  18  00:00       UTC                        3.5   
352  2017  12  19  00:00       UTC                        0.2   
353  2017  12  20  00:00       UTC      

## Catenating datasets

We already saw in the NumPy section how we can catenate arrays along an axis: axis=0 catenates vertically and axis=1 catenates horizontally, and so on. With the DataFrames of Pandas it works similarly except that the row indices and the column names require extra attention. Also note a slight difference in the name: `np.concatenate` but `pd.concat`.

Let's start by considering catenation along the axis 0, that is, vertical catenation. We will first make a helper function to easily create DataFrames for testing.

In [2]:
def makedf(cols, ind):
    data = {c : [str(c) + str(i) for i in ind] for c in cols}
    return pd.DataFrame(data, ind)

Next we will create some example DataFrames:

In [36]:
a=makedf("AB", [0,1])
a

A   B
0  A0  B0
1  A1  B1

In [37]:
b=makedf("AB", [2,3])
b

A   B
2  A2  B2
3  A3  B3

In [38]:
c=makedf("CD", [0,1])
c

C   D
0  C0  D0
1  C1  D1

In [64]:
d=makedf("BC", [2,3])
d

B   C
2  B2  C2
3  B3  C3

In the following simple case, the `concat` function works exactly as we expect it would:

In [41]:
pd.concat([a,b])   # The default axis is 0

A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

The next, however, will create duplicate indices:

In [53]:
r=pd.concat([a,a])
r

A   B
0  A0  B0
1  A1  B1
0  A0  B0
1  A1  B1

In [56]:
r.loc[0,"A"]

0    A0
0    A0
Name: A, dtype: object

This is not usually what we want! There are three solutions to this. Firstly, deny creation of duplicated indices by giving the `verify_integrity` parameter to the `concat` function:

In [57]:
pd.concat([a,a], verify_integrity=True)

ValueError: Indexes have overlapping values: Int64Index([0, 1], dtype='int64')

Secondly, we can ask for automatic renumbering of rows:

In [58]:
pd.concat([a,a], ignore_index=True)

A   B
0  A0  B0
1  A1  B1
2  A0  B0
3  A1  B1

Thirdly, we can ask for *hierarchical indexing*. More about hierarchical indexing in section XXX.

In [60]:
r2=pd.concat([a,a], keys=['first', 'second'])
r2

A   B
first  0  A0  B0
       1  A1  B1
second 0  A0  B0
       1  A1  B1

In [63]:
r2["A"]["first"][0]

'A0'

Everything works similarly, when we want to catenate horizontally:

In [65]:
pd.concat([a,c], axis=1)

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1

We have so far assumed that when concatenating vertically the column of both DataFrames are the same, and when joining horizontally the indices are the same. This is, however, not required:

In [66]:
pd.concat([a,d])

/home/jttoivon/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  """Entry point for launching an IPython kernel.


A   B    C
0   A0  B0  NaN
1   A1  B1  NaN
2  NaN  B2   C2
3  NaN  B3   C3

It expanded the non-existing cases with `NaN`s. This method is called an *outer join*, which forms the union of columns in the two DataFrames. The alternative is *inner join*, which forms the intersection of columns:

In [67]:
pd.concat([a,d], join="inner")

B
0  B0
1  B1
2  B2
3  B3

## Merging dataframes

## Aggregates and groupings

## Time series

[Pandas cheat sheet](https://github.com/pandas-dev/pandas/blob/master/doc/cheatsheet/Pandas_Cheat_Sheet.pdf)

<!--NAVIGATION-->


<a href="https://colab.research.google.com/github/jttoivon/x/blob/master/pandas.ipynb"><img align="left" src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab" title="Open and Execute in Google Colaboratory"></a>
